export enum OutgoingPostMessageEvent {
  SYNC_WIDGET_CONTEXT_LOADED = 'SYNC_WIDGET_CONTEXT_LOADED',
  SYNC_WIDGET_ERROR = 'SYNC_WIDGET_ERROR',
  SYNC_INVITATION_CREATED = 'SYNC_INVITATION_CREATED',
  SYNC_INVITATION_ERROR = 'SYNC_INVITATION_CREATED',
}

export enum IncomingPostMessageEvent {
  SYNC_CONSENTED = 'SYNC_CONSENTED',
  SYNC_WIDGET_READY = 'SYNC_WIDGET_READY',
  SYNC_MODAL_OPEN = 'SYNC_MODAL_OPEN',
  SYNC_MODAL_CLOSED = 'SYNC_MODAL_CLOSED',
}
